import Head from "next/head";
import {
  WorkingWith,
  Hero,
  Intro,
  Footer,
  Video,
  Evaluate,
  Demo,
  Navigation,
} from "@/components";
import { Bebas_Neue, IBM_Plex_Mono } from "next/font/google";

const bebasNeue = Bebas_Neue({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-bebas",
});
const ibmPlexMono = IBM_Plex_Mono({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-ibmPlexMono",
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${bebasNeue.variable} ${ibmPlexMono.variable} `}>
        <Navigation />
        <Hero />
        <Intro />
        <WorkingWith />
        <Video />
        <Evaluate />
        <Demo />
        <Footer />
      </main>
    </>
  );
}
